### ISSUE TITLE
reserved word as column name failing on yamltodb -u

### ISSUE THREAD

**Issue by lgfausak** [perseas/Pyrseas#106]
I've created a database table with a column name 'desc'.  This dumps properly in dbtoyaml, but, a subsequent yamltodb -u fails with this error:

```
yamltodb -u -H ab -U postgres newdb db.yaml
```

Traceback (most recent call last):
  File "/usr/local/bin/yamltodb", line 9, in <module>
    load_entry_point('Pyrseas==0.7.1', 'console_scripts', 'yamltodb')()
  File "/usr/local/lib/python2.7/dist-packages/Pyrseas-0.7.1-py2.7.egg/pyrseas/yamltodb.py", line 69, in main
    db.dbconn.execute(stmt)
  File "/usr/local/lib/python2.7/dist-packages/Pyrseas-0.7.1-py2.7.egg/pyrseas/lib/dbconn.py", line 81, in execute
    raise exc
psycopg2.ProgrammingError: syntax error at or near "desc"
LINE 4:     desc text)

The yaml in question is:

```
  table activity_type:
    columns:
    - id:
        not_null: true
        type: text
    - name:
        type: text
    - desc:
        type: text
    owner: autouser
    primary_key:
      activity_type_pkey:
        columns:
        - id
```

I am changing the name of the column to description.  But, it might be a safe thing to double quote all names when creating the sql to apply the diff.
