### ISSUE TITLE
yamltodb does not recognize indexes on materialized views

### ISSUE THREAD

**Issue by deuscapturus** [perseas/Pyrseas#160]
A index specified in a materlized view will not be created by `yamltodb`.  If the index already exists dbtoyaml will remove it.

However, `dbtoyaml` will succesfully add indexes on materliazed views.

```
  materialized view course_authors_unnested:
    definition: " SELECT DISTINCT courses.id AS course_id,\n    unnest(courses.author_ids)\
      \ AS author_id\n   FROM courses;"
    indexes:
      course_authors_indexed_by_course:
        keys:
        - course_id
    owner: ladmin
    privileges:
    - ladmin:
      - all
    - lapp:
      - truncate
      - insert
      - delete
      - select
      - update
    with_data: true
```

**Comment by jmafc** [comment]
It seems like you have the utility names backwards. The ouput YAML shown above, I assume, was created by `dbtoyaml`?  Further, I'm guessing when you used that output with `yamltodb` instead of generating SQL like `CREATE INDEX course_authors_indexed_by_course ...` it generated `DROP INDEX ...` instead?

**Comment by deuscapturus** [comment]
@jmafc Exactly

**Comment by jmafc** [comment]
This is the same as #82 which, as you may see, was fixed by af5b0564, but only in the master branch. If possible, could you please check your test case against an install from master? You could also apply the two-line change to `pyrseas/dbobject/table.py` from the fix, and verify that it works for you. Please let us know if you think we should merge the fix to the r0.7 branch, so that it may eventually be available in a 0.7.x release (if we do have another maint release).

**Comment by deuscapturus** [comment]
Thank you @jmafc.  I've tried the latest master branch.  This issue is still not resolved.

**Comment by jmafc** [comment]
OK. Can you please look at the test `test_view_index` in `tests/dbobject/test_matview.py` (master branch) and see if you can tell us how it differs from your case? Does your matview depend on some other types/functions (see issues tagged "dependencies" which we're working on for a 0.8 release)? Or perhaps it's that the index was created at the same time as the matview (our case tests index creation *after* a matview is in existence).

**Comment by jmafc** [comment]
I've created the following test YAML file, based on the info in the YAML you provided:
```yaml
extension plpgsql:
  description: PL/pgSQL procedural language
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  materialized view cau:
    definition: |2-
       SELECT DISTINCT ca.cid,
          unnest(ca.aids) AS aid
         FROM ca;
    indexes:
      cab:
        keys:
        - cid
    with_data: true
  table a:
    columns:
    - id:
        not_null: true
        type: integer
    - c2:
        type: text
    primary_key:
      a_pkey:
        columns:
        - id
  table c:
    columns:
    - id:
        not_null: true
        type: integer
    - c2:
        type: text
    primary_key:
      c_pkey:
        columns:
        - id
  table ca:
    columns:
    - cid:
        not_null: true
        type: integer
    - aids:
        not_null: true
        type: integer[]
    foreign_keys:
      ca_cid_fkey:
        columns:
        - cid
        references:
          columns:
          - id
          schema: public
          table: c
    primary_key:
      ca_pkey:
        columns:
        - cid
        - aids
```
I added the extra tables, primary keys to foreign keys to make it more realistic and possibly elicit problems with dependencies. I tested against a PG 9.4.11 database (client is 9.6.2) using Python 3.5.3 (also tried the second test with 2.7.13), in two different ways, *after* creating the `a`, `c` and `ca` tables. First, the matview was created in one pass and the index added in a second pass. Second, both the matview and the index were created in a single pass. I did not encounter any problems in my tests. The tests were done against the Pyrseas master branch, last commit 8297929.

Therefore, I need more info from you, for example, versions of PG/Python, steps taken and errors/result output, and maybe try the test above in your environment.
