### ISSUE TITLE
yamltodb: incorrect create order of scripts with materialized view

### ISSUE THREAD

**Issue by Sergey778** [perseas/Pyrseas#171]
## Problem 
Pyrseas creates a materialized view before the tables on which it depends when using yamltodb.
## Reproducing
Load following script in db using yamltodb:

```yaml
extension plpgsql:
  description: PL/pgSQL procedural language
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  materialized view concept_subsumption:
    definition: "SELECT test.name FROM test;"
    indexes:
      name_index:
        keys:
        - name
        unique: true
    with_data: false
  table test:
    columns:
    - name:
        not_null: true
        type: text
    primary_key:
      pk_test:
        columns:
        - name
```

Problem exists on master-branch.

**Comment by jmafc** [comment]
Did you create that YAML by hand or with `dbtoyaml` (in master)? If you look at the test `tests/dbobject/test_matview.py MatViewToSqlTestCase test_create_view()` you'll notice that the materialized view has an additional attribute: `depends_on`.  This is part of the dependency tracking changes implemented in master (but not yet fully documented). If I add the lines:
```yaml
    depends_on:
      - table test
```
after the `definition` line, `yamltodb` creates the table first.

**Comment by Sergey778** [comment]
This example I created by hands, but in my main project dbtoyaml generated script without `depends_on` attribute.

**Comment by jmafc** [comment]
Did you use the `dbtoyaml` from `master` in your main project? If you were previously using an installed version, please double check (if you run `dbtoyaml --version`, it should show 0.8.dev0, whereas the one installed via pip would show 0.7.3 or similar). In any case, after running the corrected YAML file into a database, if I run `dbtoyaml` on it, both Python 2 and 3 show the `depends_on` attribute:

Python 2:
```yaml
  materialized view concept_subsumption:
    definition: " SELECT test.name\n   FROM test;"
    depends_on:
    - table test
```

Python 3:
```yaml
  materialized view concept_subsumption:
    definition: |2-
       SELECT test.name
         FROM test;
    depends_on:
    - table test
```
