### ISSUE TITLE
dbtoyaml - analyze functions arguments and returns type

### ISSUE THREAD

**Issue by excavador** [perseas/Pyrseas#183]
Would be very nice to have information about function arguments and types.

For instance
```
create table foo(
    a int unique
);

create table bar(
    b int primary key references foo(a)
);

create or replace function f(value foo, c int) returns bar as $$
SELECT ROW(value.*)::bar;
$$ language sql;
```

Actual output (pyrseas 0.8.0):
```
schema public:
  ...
  function f(value foo, c integer):
    language: sql
    owner: postgres
    returns: bar
    source: '

      SELECT ROW(value.*)::bar;

      '
  owner: postgres
  privileges:
  - PUBLIC:
    - all
  - postgres:
    - all
...
```

Desired output:
```
schema public:
  ...
  function f(public.foo, integer):
    arguments:
      - name: value
         schema: public
         table: foo
      - name: c
         type: integer
    returns:
      - schema: public 
         table: bar
    language: sql
    owner: postgres
    returns: bar
    source: '

      SELECT ROW(value.*)::bar;

      '
  owner: postgres
  privileges:
  - PUBLIC:
    - all
  - postgres:
    - all
...

```
or something like that
