### ISSUE TITLE
dbtoyaml - analyze view columns data types

### ISSUE THREAD

**Issue by excavador** [perseas/Pyrseas#184]
Would be very nice to see the view columns data types.

Example:
```
create table foo(
    a int unique
);

create table bar(
    b int primary key references foo(a)
);

create or replace view view_foo_as_bar as
select (row(foo.*)::bar).*, foo, 5 as const from foo;
```
actual output:
```
  view view_foo_as_bar:
    definition: " SELECT (ROW(foo.a)::bar).b AS b,\n    foo.*::foo AS foo,\n    5\
      \ AS const\n   FROM foo;"
    depends_on:
    - table foo
    owner: postgres

```

desired output:
```
  view view_foo_as_bar:
     columns:
       - b:
            type: integer
            references:
              schema: public
              table: foo
              column: a
        - foo: 
             type: public.foo
             references:
               schema: public
               table: foo
         - const:
             type: integer
    definition: " SELECT (ROW(foo.a)::bar).b AS b,\n    foo.*::foo AS foo,\n    5\
      \ AS const\n   FROM foo;"
    depends_on:
    - table foo
    owner: postgres
```
or something like that

**Comment by excavador** [comment]
I suppose my team can prepare patch for that.
I need to know, it's possible to merge it to upstream (in theory) or we should consider forking.
Thank you.

**Comment by jmafc** [comment]
My response to this is more or less the same as for #183, except that it should be easier to fetch the view column information from `pg_attribute` at the same time we retrieve columns for regular/partitioned/foreign tables, so there's less concern with respect to performance degradation. Of course, if we do it for views, it should also apply to materialized views, perhaps mostly by inheritance. And the `depends_on` is already present on views.

**Comment by jmafc** [comment]
BTW, on my system (PG 9.6.7), the third column of the view is named `?column?` when you use "\d view_foo_as_bar" in psql. Did you redefine it as `AS const` before running `dbtoyaml`?

**Comment by excavador** [comment]
@jmafc yes, sorry, copy-paste wrong sql file.

**Comment by tbussmann** [comment]
I don't see where it would be possible to extract the information for the `references` sections in the desired output. The columns could be constructed of arbitrary complex expressions. The `type` information can be found in `pg_attribute` as @jmafc explained.
What imho in the current implementation is missing is the dependency on the type `bar` in the `depends_on` clause. This dependency can be found in `pg_depend`. Quite handy queries to examine this data can be found in the [PostgreSQL wiki](https://wiki.postgresql.org/wiki/Pg_depend_display).
I tied something like 
```
SELECT --*,
    pg_describe_object(classid, objid, objsubid) AS "depender object identity",
    pg_describe_object(refclassid, refobjid, refobjsubid) AS "referenced object identity",
    CASE deptype
        WHEN 'p' THEN 'pinned'
        WHEN 'x' THEN 'auto extension'
        WHEN 'e' THEN 'extension'
        WHEN 'i' THEN 'internal'
        WHEN 'a' THEN 'automatic'
        WHEN 'n' THEN 'normal'
    END AS "dependency type"
FROM pg_catalog.pg_depend 
WHERE objid >= 16384 AND refobjid >= 16384
ORDER BY objid, objsubid, refobjid, refobjsubid
;
```

**Comment by excavador** [comment]
```
pyrseas_bug=# \d view_foo_as_bar;
View "public.view_foo_as_bar"
 Column |  Type   | Modifiers
--------+---------+-----------
 b      | integer |
 foo    | foo     |
 const  | integer |
```
Seems like psql in some way detect view datatypes, and it's possible to investigate it from pyrseas without analyzing the columns expessions

**Comment by excavador** [comment]
So, I understand your position described in #183 and in general can agree.
But in this particular case adding extra information change nothing from dbtoyaml/yamltodb/other tools point of view, but very usefull for some another purposes.

We can easy extend this output, but in result we need to fork pyrseas or make second pass after dbtoyaml run.

Would be very great extract this information and include it to yaml file.
It brokes nothing, but in our particular case helps a lot.

**Comment by jmafc** [comment]
Oleg, psql gets its type info from `pg_attribute` (you can see the query if you use `psql -E`). We already query `pg_attribute` in `pyrseas/dbobject/column.py` so, as I mentioned above, it would be easy to get that for views and materialized views in the same query.

**Comment by excavador** [comment]
@jmafc Oh, now got it. You will include this information to dbtoyaml output.
Thank you!

**Comment by jmafc** [comment]
I have started to create a ViewToMapTestCase based on your example (except using table/view names `t1`, `t2` and `v1` and column names `c1` and `c2`. The current definition, with Py3, is output as follows:
```yaml
view v1:
  definition: |2-
     SELECT (ROW(t1.c1)::public.t2).c2 AS c2,
        t1.*::public.t1 AS t1,
        5 AS const
       FROM public.t1;
  depends_on:
  - table t1
```
Looking at your "desired output" however, I think we should only output the data types for the columns, i.e.,
```yaml
  columns:
  - c2:
      type: integer
  - t1:
      type: t1
  - const:
     type: integer
```
That is, we will *not* include those `references` sections (`references` is not a good term because in SQL it FOREIGN KEY definitions and views don't abide by any referential integrity rules).
