### ISSUE TITLE
dbtoyaml results in KeyError on schema it should be ignoring

### ISSUE THREAD

**Issue by yissachar** [perseas/Pyrseas#186]
```
$ dbtoyaml -U postgres mydb -W -n public -t foo -t bar -t master -O -x
```

Results in the following error:

```
KeyError: ('"another-schema"', 'master')
```

Both schemas are identical, the only difference being the name. It is confusing because it doesn't seem like `another-schema` should be read at all.

**Comment by jmafc** [comment]
We read all the schemas because sometimes an object in one schema references an object in another schema. The filtering of `-n` and `-t` only occurs as a post-processing step and unfortunately, although we tried to emulate the options from `pg_dump` we did not establish rules or policies for dealing with problems as the one you show (IIRC this may have been reported earlier). If you exclude the `-n public`, I think the KeyError will not occur but you will be shown both `public.master` and `another-schema.master`. I'm going to have to check and see how pg_dump behaves in such an instance and whether we can do something similar.

**Comment by jmafc** [comment]
Now that I took the time to create a test case, I'm afraid I can't reproduce your reported problem. Here's the `dbtoyaml -Ox` output of the database:
```yaml
extension plpgsql:
  description: PL/pgSQL procedural language
  schema: pg_catalog
  version: '1.0'
schema another-schema:
  table master:
    columns:
    - col:
        type: text
schema public:
  description: standard public schema
  table bar:
    columns:
    - l:
        type: text
  table foo:
    columns:
    - k:
        type: integer
  table master:
    columns:
    - c1:
        type: integer
```
If I try it with your original command line options or without the `-n public`, I get no error. I tested both under the r0.8 and the master branches.
Please advise more details of your configuration that may be relevant: Pyrseas version, Postgres version, any other objects or references betweeen them that may be significant?
