### ISSUE TITLE
Multiline Strings (source: |2) Output Unstable

### ISSUE THREAD

**Issue by salamsp** [perseas/Pyrseas#238]
I have Python 3.9 installed on my PC, but command

dbtoyaml --multiple-files db_development

produced output source: |2  and usual  source: "\n<<local>>...
in the same call. Is it possible to setup this implicitly?

**Comment by jmafc** [comment]
I'm not sure I follow exactly, but let me try. I assume you have two or more functions in your database and, I'm guessing, one of the function's source was output different than the other (and further, perhaps you prefer one style over the other). If that's the case, and IIRC that's a "feature" of the YAML output processor, i.e., it uses one style based on the length of the text or some other parameter. On one of my test databases, I see three "text styles":
```yaml
 function ...:
   language: sql
   source: |-
      SELECT CASE WHEN ...
      ELSE ...
...
 function ...:
   language: plpgsql
   source: "\ndeclare ..."
...
  view ...:
    definition: |2-
      SELECT ( ...
```
In fact all of the views use the ": |2-" which IIRC means the indentation is two spaces. The SQL functions, which use ":|-" have no indentation (or arbitrary indentation. The PLPGSQL functions use a single string enclosed in double quotes, probably because they start with a newline character and it would be difficult for YAML (which in essence uses newlines to replace the "}," delimiters that you find in JSON) to parse something like the following:
```yaml
  source: |-

     declare ...
```
