### ISSUE TITLE
sfunc and finalfunc attributes of an aggregate should not include arguments

### ISSUE THREAD

**Issue by jmafc** [perseas/Pyrseas#54]
An aggregate such as the following (thanks, Josh Berkus):

``` sql
CREATE AGGREGATE mode(boolean) (
    SFUNC = mode_bool_state,
    STYPE = INT[],
    FINALFUNC = mode_bool_final,
    INITCOND = '{0,0}');
```

is output by dbtoyaml as:

``` yaml
  aggregate mode(boolean):
    finalfunc: mode_bool_final(integer[])
    initcond: '{0,0}'
    sfunc: mode_bool_state(integer[],boolean)
    stype: integer[]
```

The function arguments shown for `finalfunc` and `sfunc` are unnecessary since they can be derived from `stype` and the arguments to the aggregate. It should suffice for dbtoyaml to output:

``` yaml
 aggregate mode(boolean):
    finalfunc: mode_bool_final
    initcond: '{0,0}'
    sfunc: mode_bool_state
    stype: integer[]
```

which more closely parallels the CREATE AGGREGATE statement.
