### ISSUE TITLE
Can't define Augmenter function source directly if it includes audit column lookups

### ISSUE THREAD

**Issue by rhunwicks** [perseas/Pyrseas#64]
If you are specifying a custom audit function it seems intuitive to specify the source directly, rather than via a function template (because you only need one copy of the function), but if you do that you can't use the {{ }} notation for column lookups because
`CfgFunction.apply()` attempts to replace the column name with a matching function template. Perhaps it should only do the function template substitution if the source starts and ends with {{ and }} rather than just contains them?

I would expect the following to be valid:

``` yaml
augmenter:
  audit_columns:
    custom:
      columns:
      - created_timestamp
      - created_by_user
      - modified_timestamp
      - modified_by_user
      triggers:
      - custom_audit
  functions:
    custom_audit():
      description: |-
        Maintain created and modified user and timestamp audit columns
      language: plpgsql
      returns: trigger
      security_definer: true
      source: |2-
        BEGIN
          IF TG_OP = 'INSERT' THEN
            NEW.{{created_timestamp}} := CURRENT_TIMESTAMP::timestamp(0);
            NEW.{{created_by_user}} := pyrseas.get_session_variable('audit_user', SESSION_USER);
          ELSIF TG_OP = 'UPDATE' THEN
            NEW.{{created_timestamp}} := OLD.created_timestamp;
            NEW.{{created_by_user}} := OLD.created_by;
          END IF;
          NEW.{{modified_timestamp}} := CURRENT_TIMESTAMP::timestamp(0);
          NEW.{{modified_by_user}} := pyrseas.get_session_variable('audit_user', SESSION_USER);
          RETURN NEW;
        END;
  triggers:
    custom_audit:
      events:
      - insert
      - update
      level: row
      name: '{{table_name}}_20_audit'
      procedure: custom_audit()
      timing: before
```
