### ISSUE TITLE
YAML syntax for specifying default auditing for all tables in a schema

### ISSUE THREAD

**Issue by rhunwicks** [perseas/Pyrseas#65]
Ideally, I'd like to be able to specify auditing at the schema level, i.e. for all tables in the schema, rather than have to specify it for each table individually - it doesn't seem very DRY to create the table definition in my `schema.yaml` and then have to immediately add it to my `augment.yaml`

Something like:

``` yaml
schema app_schema:
  audit_columns: default
schema other_schema:
  table some_random_table:
    audit_columns: created_date_only
```

It would also be good to allow overrides to the schema-level default auditing:

``` yaml
schema app_schema:
  audit_columns: modified_only
  table some_important_table:
    audit_columns: full
```
