### ISSUE TITLE
Indexes that have WHERE predicates behaving wrongly

### ISSUE THREAD

**Issue by Jokipii** [perseas/Pyrseas#76]
Indexes that have WHERE predicates behaving wrongly

my original index:

```
CREATE INDEX edit_idx_open_edits_open_time
  ON edit
  USING btree
  (open_time)
  WHERE status = 1;
```

generated yaml

```
      edit_idx_open_edits_open_time:
        keys:
        - open_time):
            opclass: '1'
```

and when index is generated back:

```
CREATE INDEX edit_idx_open_edits_open_time ON edit (open_time) 1);
```
