### ISSUE TITLE
yamltodb: error when altering extension owner

### ISSUE THREAD

**Issue by pau** [perseas/Pyrseas#88]
Running yamltodb generated SQL statement for extension owner throws:

``` bash
ERROR:  syntax error at or near "OWNER"
```

OWNER does not seem to be a valid form according to http://www.postgresql.org/docs/9.3/static/sql-alterextension.html.
## Example

I have two databases that use the `citext` extension.

```
                         List of installed extensions
  Name  | Version | Schema |                   Description                    
--------+---------+--------+--------------------------------------------------
 citext | 1.0     | public | data type for case-insensitive character strings
```

I use `dbtoyaml` and the section that is relevant to `citext` is

``` yaml
extension citext:
  description: data type for case-insensitive character strings
  owner: postgres
  schema: public
  version: '1.0'
```

`yamltodb` then generates the following SQL statement

``` sql
ALTER EXTENSION citext OWNER TO postgres;
```

and I get the following error when I run that statement

``` bash
ERROR:  syntax error at or near "OWNER"
LINE 1: ALTER EXTENSION citext OWNER TO postgres;
```
