### ISSUE TITLE
yamltodb running under Python3 outputs bytes objects instead of strings

### ISSUE THREAD

**Issue by jmafc** [perseas/Pyrseas#92]
Given an empty database and the following YAML file (abbreviated):

``` yaml
schema public:
  ...
   table t1:
    columns:
    - c1:
        type: integer
    - c2:
        type: text
```

the command `yamltodb dbname test.yaml` when run under Python 3 (tested under Python 3.2, 3.3 and 3.4), results in the following, either to terminal or to a file:

``` sql
b'CREATE TABLE t1 (\n    c1 integer,\n    c2 text);\n'
b'ALTER TABLE t1 OWNER TO dba;\n'
```

Under Python 2, the expected UTF-8 stream is output instead.
